set(REXC_STDLIB_SOURCE "")
foreach(REXC_STDLIB_RX_SOURCE IN LISTS REXC_STDLIB_RX_SOURCES)
	file(READ "${REXC_STDLIB_RX_SOURCE}" REXC_STDLIB_RX_TEXT)
	string(APPEND REXC_STDLIB_SOURCE "// ${REXC_STDLIB_RX_SOURCE}\n")
	string(APPEND REXC_STDLIB_SOURCE "${REXC_STDLIB_RX_TEXT}\n")
endforeach()

configure_file("${REXC_STDLIB_TEMPLATE}" "${REXC_STDLIB_OUTPUT}" @ONLY)
